baseURL = "https://lberrymage.dev/"
languageCode = "en-us"
title = "Logan's Blog"
theme = "WonderMod"

[params]
defaultTheme = "dark"

  [params.homeInfoParams]
  title = "Welcome to the rabbit hole."
  content = "Thoughts on security, privacy, development, and Android."
